"""Generate a copy/paste-ready Markdown change-ticket summary.

This module turns an existing PreflightOps risk assessment result (plus the
parsed change request) into a structured Markdown "change summary" that a human
can paste into ServiceNow, Jira, a CAB review, or an internal approval request.

The layout is **template-driven**. A template controls the document title, the
section order and headings, the approval / deployment-window wording, and the
notes footer. The built-in :data:`DEFAULT_TEMPLATE` reproduces the original
output exactly, and teams can supply their own template (a plain dict or a YAML
file via :func:`load_template_file`) to match their own change-management format
without code changes. Templates need no extra dependencies.

IMPORTANT: This is **not** a real ServiceNow or Jira API integration. It makes
no network calls and requires no authentication, tokens, or external services.
It only formats data PreflightOps already computed into a change-record-style
Markdown document. Real ServiceNow/Jira API integration is future work (see the
roadmap).
"""

import copy
from typing import Any

import yaml

# Approval recommendation text keyed by risk level (exact wording per issue #11).
APPROVAL_BY_LEVEL = {
    "LOW": "Standard team review is usually sufficient.",
    "MEDIUM": "Service owner review recommended before deployment.",
    "HIGH": "Senior engineering or platform review recommended before deployment.",
    "CRITICAL": (
        "Deployment should not proceed until critical gaps are resolved and "
        "senior approval is obtained."
    ),
}

# Recommended deployment-window text keyed by risk level (exact wording per issue #11).
DEPLOYMENT_WINDOW_BY_LEVEL = {
    "LOW": "Normal deployment window is acceptable.",
    "MEDIUM": "Deploy during a monitored window with service owner availability.",
    "HIGH": ("Use a low-traffic deployment window with rollback owner and monitoring confirmed."),
    "CRITICAL": (
        "Do not deploy until critical gaps are resolved. If deployment is "
        "unavoidable, use an approved emergency change process."
    ),
}

# Fallbacks for missing plan sections.
NO_ROLLBACK_PLAN = "No rollback plan detected."
NO_MONITORING_PLAN = "No monitoring plan detected."
NO_VALIDATION_PLAN = "No validation plan detected."

# Fallback for a missing business-impact statement.
NO_BUSINESS_IMPACT = (
    "Business impact was not provided. Service owner should define customer, "
    "operational, or revenue impact before approval."
)

NOTES_FOOTER = (
    "Generated by PreflightOps as a copy/paste-ready change summary for "
    "ServiceNow, Jira, CAB review, or internal approval workflows."
)

# Map a missing control to a human-readable recommended action.
ACTION_BY_CONTROL = {
    "service_owner": "Assign a named service owner before deployment.",
    "runbook": "Add a runbook link for the service.",
    "business_impact": "Document the business impact of this change.",
    "rollback_plan": "Provide a valid, tested rollback plan.",
    "monitoring_plan": ("Define a monitoring plan (dashboards, alerts, success criteria)."),
    "validation_plan": "Add a post-deploy validation plan.",
}


def _is_empty(value) -> bool:
    if value is None:
        return True
    if isinstance(value, str):
        return not value.strip()
    if isinstance(value, (list, dict, tuple, set)):
        return len(value) == 0
    return False


def _render_rollback_plan(value) -> list:
    """Render the rollback plan, or the fallback line when absent."""
    if _is_empty(value):
        return [NO_ROLLBACK_PLAN]
    return [str(value).strip()]


def _render_monitoring_plan(value) -> list:
    """Render the monitoring plan as bullet lines, or the fallback when absent."""
    if _is_empty(value):
        return [NO_MONITORING_PLAN]
    if isinstance(value, dict):
        lines = []
        for key, detail in value.items():
            label = str(key).replace("_", " ")
            if isinstance(detail, (list, tuple, set)):
                rendered = ", ".join(str(item) for item in detail)
            else:
                rendered = str(detail)
            lines.append(f"- {label}: {rendered}")
        return lines or [NO_MONITORING_PLAN]
    if isinstance(value, (list, tuple, set)):
        return [f"- {item}" for item in value]
    return [str(value).strip()]


def _render_validation_plan(value) -> list:
    """Render the validation plan as bullet lines, or the fallback when absent."""
    if _is_empty(value):
        return [NO_VALIDATION_PLAN]
    if isinstance(value, (list, tuple, set)):
        return [f"- {item}" for item in value]
    if isinstance(value, dict):
        return [f"- {key}: {detail}" for key, detail in value.items()]
    return [str(value).strip()]


def _render_findings(triggered: list) -> list:
    """Render each triggered finding as a bullet, with a no-findings fallback."""
    if not triggered:
        return ["- No risk findings detected."]
    return [f"- {rule.get('description', '')}".rstrip() for rule in triggered]


def _render_actions(missing_controls: list, recommendation: str) -> list:
    """Build the recommended-actions list from missing controls + recommendation."""
    actions = []
    for control in missing_controls or []:
        actions.append(
            "- " + ACTION_BY_CONTROL.get(control, f"Address missing control: {control}.")
        )
    if recommendation:
        actions.append(f"- {recommendation.strip()}")
    if not actions:
        actions.append("- No additional actions required.")
    return actions


# ---------------------------------------------------------------------------
# Section content renderers
#
# Each renderer takes the assessment ``result``, the parsed ``change`` dict, and
# the active ``template`` and returns the list of Markdown body lines for one
# section. A template's sections reference these by ``content`` key.
# ---------------------------------------------------------------------------
def _content_change_title(result, change, template) -> list:
    return [change.get("title") or "Not specified"]


def _content_service(result, change, template) -> list:
    return [result.get("service", "") or "Not specified"]


def _content_environment(result, change, template) -> list:
    return [result.get("environment", "") or "Not specified"]


def _content_business_impact(result, change, template) -> list:
    business_impact = result.get("business_impact")
    if _is_empty(business_impact):
        business_impact = NO_BUSINESS_IMPACT
    return [business_impact]


def _content_risk_level(result, change, template) -> list:
    return [result.get("risk_level", "") or "Not specified"]


def _content_risk_score(result, change, template) -> list:
    return [f"{result.get('risk_score', 0)}/100"]


def _content_required_approvals(result, change, template) -> list:
    approvals = template["approvals"]
    risk_level = result.get("risk_level", "")
    return [approvals.get(risk_level) or approvals.get("MEDIUM", "")]


def _content_rollback_plan(result, change, template) -> list:
    return _render_rollback_plan(change.get("rollback_plan"))


def _content_monitoring_plan(result, change, template) -> list:
    return _render_monitoring_plan(change.get("monitoring_plan"))


def _content_validation_plan(result, change, template) -> list:
    return _render_validation_plan(change.get("validation_plan"))


def _content_deployment_window(result, change, template) -> list:
    windows = template["deployment_windows"]
    risk_level = result.get("risk_level", "")
    return [windows.get(risk_level) or windows.get("MEDIUM", "")]


def _content_risk_findings(result, change, template) -> list:
    return _render_findings(result.get("triggered_rules", []))


def _content_recommended_actions(result, change, template) -> list:
    return _render_actions(result.get("missing_controls", []), result.get("recommendation", ""))


def _content_notes(result, change, template) -> list:
    return [template["notes"]]


# Registry of the content keys a template section may reference.
CONTENT_RENDERERS = {
    "change_title": _content_change_title,
    "service": _content_service,
    "environment": _content_environment,
    "business_impact": _content_business_impact,
    "risk_level": _content_risk_level,
    "risk_score": _content_risk_score,
    "required_approvals": _content_required_approvals,
    "rollback_plan": _content_rollback_plan,
    "monitoring_plan": _content_monitoring_plan,
    "validation_plan": _content_validation_plan,
    "deployment_window": _content_deployment_window,
    "risk_findings": _content_risk_findings,
    "recommended_actions": _content_recommended_actions,
    "notes": _content_notes,
}


# The built-in template. Rendering this reproduces the original ticket output
# exactly, so existing behavior is unchanged when no template is supplied.
DEFAULT_TEMPLATE: dict[str, Any] = {
    "title": "Production Change Summary",
    "sections": [
        {"heading": "Change Title", "content": "change_title"},
        {"heading": "Service", "content": "service"},
        {"heading": "Environment", "content": "environment"},
        {"heading": "Business Impact", "content": "business_impact"},
        {"heading": "Risk Level", "content": "risk_level"},
        {"heading": "Risk Score", "content": "risk_score"},
        {"heading": "Required Approvals", "content": "required_approvals"},
        {"heading": "Rollback Plan", "content": "rollback_plan"},
        {"heading": "Monitoring Plan", "content": "monitoring_plan"},
        {"heading": "Validation Plan", "content": "validation_plan"},
        {"heading": "Recommended Deployment Window", "content": "deployment_window"},
        {"heading": "Risk Findings", "content": "risk_findings"},
        {"heading": "Recommended Actions", "content": "recommended_actions"},
        {"heading": "Notes", "content": "notes"},
    ],
    "approvals": APPROVAL_BY_LEVEL,
    "deployment_windows": DEPLOYMENT_WINDOW_BY_LEVEL,
    "notes": NOTES_FOOTER,
}


def load_template(data=None) -> dict:
    """Normalize a user-supplied template into a complete template dict.

    Parameters
    ----------
    data : dict, optional
        A partial or full template. Any key that is omitted falls back to
        :data:`DEFAULT_TEMPLATE`, so a team can override just the pieces they
        care about (for example only ``sections`` or only ``approvals``). When
        ``None`` (or empty), the default template is returned unchanged.

    Recognized keys
    ---------------
    ``title``
        The ``# H1`` document title.
    ``sections``
        An ordered list of ``{"heading": str, "content": <key>}`` mappings. Each
        ``content`` must be one of :data:`CONTENT_RENDERERS`. Replaces the
        default section list entirely when provided.
    ``approvals`` / ``deployment_windows``
        Per-risk-level wording maps (``LOW`` / ``MEDIUM`` / ``HIGH`` /
        ``CRITICAL``). Merged over the defaults, so partial overrides are fine.
    ``notes``
        The footer text.

    Returns
    -------
    dict
        A fully populated template ready for :func:`generate_ticket_markdown`.

    Raises
    ------
    ValueError
        If a section is malformed or references an unknown ``content`` key.
    """
    template = copy.deepcopy(DEFAULT_TEMPLATE)
    if not data:
        return template
    if not isinstance(data, dict):
        raise ValueError("Template must be a mapping (dict).")

    if "title" in data:
        template["title"] = str(data["title"])

    if "notes" in data:
        template["notes"] = str(data["notes"])

    for key in ("approvals", "deployment_windows"):
        if key in data:
            overrides = data[key]
            if not isinstance(overrides, dict):
                raise ValueError(f"Template '{key}' must be a mapping of risk level to text.")
            merged = dict(template[key])
            merged.update({str(k): str(v) for k, v in overrides.items()})
            template[key] = merged

    if "sections" in data:
        sections = data["sections"]
        if not isinstance(sections, list) or not sections:
            raise ValueError("Template 'sections' must be a non-empty list.")
        normalized = []
        for index, section in enumerate(sections):
            if not isinstance(section, dict):
                raise ValueError(f"Template section #{index + 1} must be a mapping.")
            content = section.get("content")
            if content not in CONTENT_RENDERERS:
                valid = ", ".join(sorted(CONTENT_RENDERERS))
                raise ValueError(
                    f"Template section #{index + 1} has unknown content "
                    f"'{content}'. Valid content keys are: {valid}."
                )
            heading = section.get("heading", "")
            normalized.append({"heading": str(heading), "content": content})
        template["sections"] = normalized

    return template


def load_template_file(path) -> dict:
    """Load and normalize a template from a YAML (or JSON) file.

    The file is parsed with ``yaml.safe_load`` (which also accepts JSON) and
    passed through :func:`load_template`. No extra dependencies are required.
    """
    with open(path, encoding="utf-8") as handle:
        data = yaml.safe_load(handle)
    return load_template(data)


def generate_ticket_markdown(result: dict, change_doc=None, template=None) -> str:
    """Render a risk result as a ServiceNow/Jira-ready Markdown change summary.

    Parameters
    ----------
    result : dict
        The risk result object returned by ``assess_risk``.
    change_doc : dict, optional
        The parsed change request document (``{"change": {...}}``). Used for the
        change title and the rollback / monitoring / validation plans. When
        omitted, those sections fall back to their "not detected" text.
    template : dict, optional
        A template controlling section order, headings, and the approval /
        deployment-window / notes wording. Accepts either a normalized template
        (from :func:`load_template` / :func:`load_template_file`) or a raw
        partial template dict, which is normalized automatically. When omitted,
        :data:`DEFAULT_TEMPLATE` is used and the output is identical to before.

    Returns
    -------
    str
        A Markdown document. This is a plain text summary only — it is not sent
        to any ServiceNow or Jira API.
    """
    change = {}
    if isinstance(change_doc, dict):
        nested = change_doc.get("change")
        change = nested if isinstance(nested, dict) else {}

    template = load_template(template)

    lines = []
    lines.append(f"# {template['title']}")
    lines.append("")
    for section in template["sections"]:
        renderer = CONTENT_RENDERERS[section["content"]]
        lines.append(f"## {section['heading']}")
        lines.extend(renderer(result, change, template))
        lines.append("")

    return "\n".join(lines)
